#!/usr/bin/env bash

PYTHONPATH=.

#WALLETSERVER_URL="https://wallet.d.vega.xyz"
#NODE_URL_REST="https://n04.d.vega.xyz"
#NODE_URL_GRAPHQL="https://n04.d.vega.xyz/query"
#NODE_URL_GRPC="n04.d.vega.xyz:3002"
#
#WALLET_NAME="chris"
#WALLET_PASSPHRASE="123"


WALLETSERVER_URL="https://wallet.testnet.vega.xyz"
NODE_URL_REST="https://lb.testnet.vega.xyz"
NODE_URL_GRAPHQL="https://lb.testnet.vega.xyz/query"
NODE_URL_GRPC="n06.testnet.vega.xyz:3002"

WALLET_NAME="0xD0957B56370A06Eb3f8F3F446C3eF2E8D26395A7"
WALLET_PASSPHRASE="PNhY4WGjfvvXk3RZpVgtbTRBdbqsQJ"

#

export PYTHONPATH
export NODE_URL_GRPC
export NODE_URL_REST
export NODE_URL_GRAPHQL
export WALLETSERVER_URL
export WALLET_NAME
export WALLET_PASSPHRASE
