---

name: Auto Assign New Issues to Project

"on":
  issues:
    types: [opened]

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Add new issues to Core Current Sprint project
    steps:
      - uses: alex-page/github-project-automation-plus@f1ec7354e5be4f3e61eb052ca3caf4b7ce62c29a
        with:
          project: Core (Team Board)
          column: Incoming to triage
          repo-token: ${{ secrets.GH_NEW_CARD_TO_PROJECT }}
